### ISSUE TITLE
No Python 3.9 builds available

### ISSUE THREAD

**Issue by tpdownes** [conda-forge/crcmod-feedstock#11]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Despite #8, there are no available builds for Python 3.9.

https://anaconda.org/conda-forge/crcmod/files

**Comment by xylar** [comment]
I just make it `noarch: python`, in #10, so hopefully this is addressed.  Please reopen if you have trouble.
